name = "guagua-tools-domain"
main = "worker-proxy.js"
compatibility_date = "2026-07-28"

[[routes]]
pattern = "guagua-alvin.top"
custom_domain = true

[[routes]]
pattern = "www.guagua-alvin.top"
custom_domain = true
